// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: battle.sql

package db

import (
	"context"
)

const insertBattle = `-- name: InsertBattle :one
INSERT INTO battle_log (position, fecha) VALUES (?, ?) RETURNING id
`

type InsertBattleParams struct {
	Position string
	Fecha    int64
}

func (q *Queries) InsertBattle(ctx context.Context, arg InsertBattleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBattle, arg.Position, arg.Fecha)
	var id int64
	err := row.Scan(&id)
	return id, err
}
