on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploys to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: go build -o out/bin/chwarbot .

      - name: Deploy
        uses: ross96D/updater-upload-action@latest
        with:
          urls: http://${{ secrets.DEPLOY_TOKEN }}@${{ secrets.DEPLOY_IP_PORT }}/update
          fields: chwarbot=@out/bin/chwarbot
